.TH XMATRIX 1 "April 2024" "xmatrix 1.0" "User Commands"

.SH NAME
xmatrix \- a lightweight Matrix client for sending messages

.SH SYNOPSIS
.B xmatrix
[\fIOPTION\fR]...

.SH DESCRIPTION
\fBxmatrix\fR is a command-line Matrix client written in Bash that allows users to send messages on Matrix servers quickly and efficiently. It is designed to be minimalistic and focuses solely on sending messages.

.SH OPTIONS

.TP
.B \-h, \-\-help \fR
Print the help.

.TP
.B \-R, \-\-room \fIRoom_ID\fR
Set the room ID to send the message to.

.TP
.B \-M, \-\-message \fIMessage\fR
Set the message to send.

.TP
.B \-S, \-\-server \fIURL\fR
Set the Matrix server URL.

.TP
.B \-U, \-\-username \fIUsername\fR
Set the Matrix username.

.TP
.B \-P, \-\-password \fIPassword\fR
Set the Matrix password.

.SH EXAMPLES
Send a message to a room:
.B xmatrix -R <room_id> -M "Hello, world!"

Set custom server URL, username, and password:
.B xmatrix -S <server_url> -U <username> -P <password>

.SH AUTHOR
Written by amosnimos.

.SH COPYRIGHT
Copyright © 2024 amosnimos.
This is free software; see the source for copying conditions. There is NO warranty.
This software is released under the MIT License. See the LICENSE file for more details.
